// ressources/js/data.js

const companiesData = [
  {
    name: "Google",
    logoType: "img",
    logo: "./ressources/images/google.svg",
    logobis: "./ressources/images/google.svg",
    scale: 1,
    desc: "Leader de l'IA multimodale et de la recherche.",
    bgGradient: "from-blue-50 to-red-50",
    tools: [
      {
        name: "Gemini Advanced",
        url: "https://gemini.google.com",
        desc: "Le LLM le plus puissant de Google (Ultra 1.5). Multimodal natif (voit, entend, parle).",
        tags: ["LLM", "Payant/Gratuit"],
      },
      {
        name: "NotebookLM",
        url: "https://notebooklm.google.com",
        desc: "Outil révolutionnaire pour les profs/élèves. Transforme vos PDF en podcast et chat.",
        tags: ["Education", "RAG"],
      },
      {
        name: "Google AI Studio",
        url: "https://aistudio.google.com",
        desc: "Console développeur gratuite pour tester Gemini Pro 1.5 avec 1M tokens.",
        tags: ["Dev", "Gratuit"],
      },
      {
        name: "Illuminate",
        url: "https://illuminate.google.com",
        desc: "Transforme les papiers scientifiques complexes en dialogues audio accessibles.",
        tags: ["Recherche", "Audio"],
      },
      {
        name: "ImageFX",
        url: "https://aitestkitchen.withgoogle.com/tools/image-fx",
        desc: "Générateur d'images haute qualité (Imagen 3).",
        tags: ["Image"],
      },
    ],
  },
  {
    name: "OpenAI",
    logoType: "img",
    logo: "./ressources/images/openai.svg",
    logobis: "./ressources/images/openai.svg",
    scale: 1.2,
    desc: "Les créateurs de ChatGPT.",
    bgGradient: "from-green-50 to-emerald-50",
    tools: [
      {
        name: "ChatGPT",
        url: "https://chat.openai.com",
        desc: "L'interface standard. Accès aux modèles GPT-4o et o1 (raisonnement).",
        tags: ["LLM", "Chat"],
      },
      {
        name: "Sora",
        url: "https://openai.com/sora",
        desc: "Génération de vidéo photoréaliste (Accès restreint pour le moment).",
        tags: ["Vidéo"],
      },
      {
        name: "Canvas",
        url: "#",
        desc: "Nouvelle interface pour l'écriture longue et le code.",
        tags: ["Productivité"],
      },
      {
        name: "OpenAI Platform",
        url: "https://platform.openai.com",
        desc: "Accès API pour les développeurs.",
        tags: ["Dev"],
      },
    ],
  },
  {
    name: "Anthropic",
    logoType: "img",
    logo: "./ressources/images/anthropic.svg",
    logobis: "./ressources/images/claude.svg",
    scale: 0.8,
    desc: "Sécurité et capacités littéraires.",
    bgGradient: "from-orange-50 to-amber-50",
    tools: [
      {
        name: "Claude.ai",
        url: "https://claude.ai",
        desc: "Interface de chat. Excellent pour le code et l'écriture nuancée.",
        tags: ["LLM"],
      },
      {
        name: "Artifacts",
        url: "#",
        desc: "Fonctionnalité de Claude qui permet de visualiser le code (React, HTML) en temps réel.",
        tags: ["Code", "Visualisation"],
      },
      {
        name: "Claude Console",
        url: "https://console.anthropic.com",
        desc: "Création de prompts complexes.",
        tags: ["Dev"],
      },
    ],
  },
  {
    name: "Mistral AI",
    logoType: "img",
    logo: "./ressources/images/mistral.svg",
    logobis: "./ressources/images/mistral.svg",
    scale: 0.9,
    desc: "Le champion Français et Européen.",
    bgGradient: "from-yellow-50 to-orange-50",
    tools: [
      {
        name: "Le Chat",
        url: "https://chat.mistral.ai",
        desc: "Accès gratuit à Mistral Large 2, un modèle de niveau GPT-4.",
        tags: ["LLM", "Gratuit"],
      },
      {
        name: "Codestral",
        url: "https://mistral.ai/news/codestral/",
        desc: "Modèle spécialisé pour la programmation Python, JS, etc.",
        tags: ["Code"],
      },
      {
        name: "La Plateforme",
        url: "https://console.mistral.ai",
        desc: "API pour intégrer Mistral dans vos apps.",
        tags: ["Dev"],
      },
    ],
  },
  {
    name: "Grok (xAI)",
    logoType: "img",
    logo: "./ressources/images/grok.svg",
    logobis: "./ressources/images/grok.svg",
    scale: 1,
    desc: "L'IA d'Elon Musk connectée à X (Twitter).",
    bgGradient: "from-gray-100 to-gray-300",
    tools: [
      {
        name: "Grok 2",
        url: "https://x.com/i/grok",
        desc: "Disponible sur X Premium. Accès aux données temps réel et moins de censure.",
        tags: ["Social", "Actu"],
      },
      {
        name: "Grok Vision",
        url: "#",
        desc: "Analyse d'images et compréhension de contexte visuel.",
        tags: ["Image"],
      },
    ],
  },
  {
    name: "Perplexity",
    logoType: "img",
    logo: "./ressources/images/perplexity.svg",
    logobis: "./ressources/images/perplexity.svg",
    scale: 1.3,
    desc: "Moteur de réponse (recherche + synthèse).",
    bgGradient: "from-teal-50 to-cyan-50",
    tools: [
      {
        name: "Perplexity Pro",
        url: "https://www.perplexity.ai",
        desc: "Remplace Google. Cherche sur le web et rédige une réponse citée.",
        tags: ["Recherche"],
      },
      {
        name: "Pages",
        url: "https://www.perplexity.ai/pages",
        desc: "Génère des articles éducatifs complets à partir d'une recherche.",
        tags: ["Education"],
      },
    ],
  },
  {
    name: "DeepSeek / Chine",
    logoType: "icon",
    logo: "fa-solid fa-dragon",
    color: "text-red-600",
    desc: "Modèles chinois haute performance (Maths/Code).",
    bgGradient: "from-red-50 to-rose-50",
    tools: [
      {
        name: "DeepSeek Chat",
        url: "https://chat.deepseek.com",
        desc: "Incroyable pour les maths et le code. Utilise le 'Chain of Thought'.",
        tags: ["Maths", "Code"],
      },
      {
        name: "Qwen (Alibaba)",
        url: "https://tongyi.aliyun.com",
        desc: "Série de modèles open-source très puissants.",
        tags: ["Open Source"],
      },
    ],
  },
  {
    name: "MiniMax",
    logoType: "img",
    logo: "./ressources/images/minimax.png",
    logobis: "./ressources/images/minimax-color.svg",
    scale: 1.8,
    desc: "Géant chinois (Vidéo/Texte).",
    bgGradient: "from-purple-50 to-pink-50",
    tools: [
      {
        name: "MiniMax",
        url: "https://www.minimax.io",
        desc: "Modèles de texte très performants (abab 6.5).",
        tags: ["LLM"],
      },
      {
        name: "Hailuo AI",
        url: "https://hailuo.ai",
        desc: "Génération de vidéo impressionnante (concurrent de Sora).",
        tags: ["Vidéo"],
      },
    ],
  },
  // Ajoutez DeepSeek, Anthropic, etc. ici...
  {
    name: "Éducation",
    badge: "Spécial Profs",
    logoType: "icon",
    logo: "fa-solid fa-graduation-cap",
    size: "text-3xl",
    color: "text-indigo-600",
    showName: true,
    desc: "Outils pédagogiques transversaux.",
    bgGradient: "from-indigo-50 to-blue-100",
    tools: [
      {
        name: "NotebookLM (Google)",
        url: "https://notebooklm.google.com",
        desc: "Chargez vos cours PDF et créez des quiz ou des résumés auto.",
        tags: ["Indispensable"],
      },
      {
        name: "Khanmigo",
        url: "https://www.khanacademy.org/khan-labs",
        desc: "Tuteur socratique de Khan Academy pour les maths et le code.",
        tags: ["Tuteur"],
      },
      {
        name: "ChatGPT Edu",
        url: "https://openai.com/index/chatgpt-edu/",
        desc: "Version sécurisée pour les universités.",
        tags: ["Instistution"],
      },
      {
        name: "Perplexity",
        url: "https://perplexity.ai",
        desc: "Pour vérifier les sources et faire des recherches bibliographiques.",
        tags: ["Recherche"],
      },
      {
        name: "Gamma",
        url: "https://gamma.app",
        desc: "Génère des présentations (PowerPoint) complètes à partir d'un prompt.",
        tags: ["Productivité"],
      },
    ],
  },
];
